baseURL = "https://blog.a10y.dev/"
languageCode = "en-us"
#theme = ["hugo-embed-pdf-shortcode", "poison"]
theme = ["hugo-embed-pdf-shortcode", "terminal"]
enableInlineShortcodes = true
paginate = 10
pluralizelisttitles = false   # removes the automatically appended "s" on sidebar entries
googleAnalytics = "G-1C1TZNME8X"

# NOTE: If using Disqus as commenting engine, uncomment and configure this line
# disqusShortname = "yourDisqusShortname"

[params]
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "Systems in Everything"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "readinglist"
        name = "Reading List"
        url = "https://a10y.notion.site/Duffy-s-Reading-List-b59edb2266624ab0a0d4b03ace0c5ded"



[taxonomies]
    series = 'series'
    tags = 'tags'
